kind: Service
apiVersion: v1
metadata:
  name: joke-app-service
  labels:
    app: joke-app
    environment: production
  namespace: joke-app-ns
spec:
  type: NodePort
  selector:
    app: joke-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30082