apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-traffic-lens
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-traffic-lens
  template:
    metadata:
      name: kube-traffic-lens
      labels:
        app: kube-traffic-lens
    spec:
      containers:
        - name: app
          image: sachinthokal/kube-traffic-lens-app@sha256:e236b37db01d81529a3bb59da0693c10402bd36ab97fb6c69550516f724dfc35
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v1.0.0"
            - name: APP_ENVIRONMENT
              value: "production"
