apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    # 1. Official Helm Chart
    - repoURL: 'https://kubernetes.github.io/ingress-nginx'
      chart: ingress-nginx
      targetRevision: 4.10.1
      helm:
        valueFiles:
          - $values/cluster-addons/ingress-nginx/values.yaml
    # 2. Self Git Repo - values.yaml
    - repoURL: 'https://github.com/sachinthokal/argocd-for-devops.git'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true