apiVersion: v1
kind: Secret
metadata:
  name: secrets-store-creds
  namespace: k8s-app
type: Opaque
stringData:
  clientid: "3d9XXX4-XXXX-XXXX-XXXX-31c1XXXXXa4825"
  clientsecret: "9XX8Q~-XXXXXXXXXXXXXXXXXXXXXX.f"