kind: ConfigMap
apiVersion: v1
metadata:
  name: stel-config
  namespace: stel-ns
data:
  DB_URL: "jdbc:postgresql://postgres-service:5432/stelcom_db"
  DB_DRIVER: "org.postgresql.Driver"
  DB_USER: "stelcom_admin"

  schema.sql: |
    CREATE TABLE IF NOT EXISTS subscribers (
      id BIGSERIAL PRIMARY KEY,
      msisdn VARCHAR(15) UNIQUE NOT NULL,
      subscriber_name VARCHAR(100) NOT NULL,
      balance NUMERIC(10, 2) DEFAULT 0.00,
      daily_data VARCHAR(50) DEFAULT '1.5 GB / 1.5 GB',
      active_plan VARCHAR(100) DEFAULT 'UNLTD_28D_1.5GB',
      plan_validity DATE DEFAULT CURRENT_DATE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS recharge_transactions (
        id BIGSERIAL PRIMARY KEY,
        conv_id VARCHAR(100) NOT NULL,
        msisdn VARCHAR(15) NOT NULL,
        plan_id VARCHAR(50) NOT NULL,
        amount NUMERIC(10, 2) NOT NULL,
        status VARCHAR(20) NOT NULL,
        txn_ref VARCHAR(100) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Real PostgreSQL Upsert
    INSERT INTO subscribers (msisdn, subscriber_name, balance, daily_data, active_plan, plan_validity)
    VALUES ('9876543210', 'Sachin Thokal', 142.50, '1.25 GB / 1.5 GB', 'UNLTD_28D_1.5GB', CURRENT_DATE)
    ON CONFLICT (msisdn) DO NOTHING;