kind: Secret
apiVersion: v1
metadata:
  name: stel-db-secrets
  namespace: stel-ns
type: Opaque
data:
  DB_PASSWORD: U3RlbGNvbVNlY3VyZVBhc3MyMDI2             # StelcomSecurePass2026
  GATEWAY_API_KEY: c3RlbGNvbS1zZWNyZXQta2V5LTk5ODg=     # stelcom-secret-key-9988
  
  