apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: stel-rate-limit
  namespace: stel-ns
plugin: rate-limiting
config:
  minute: 5
  policy: local
  error_code: 429
  error_message: "API Rate limit exceeded! Please slow down."