apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: stel-global-prometheus
  labels:
    konghq.com/plugin: "prometheus"
plugin: prometheus
config:
  per_consumer: true
  status_code_metrics: true
  latency_metrics: true
  bandwidth_metrics: true