apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: stel-correlation-id
  namespace: stel-ns
plugin: correlation-id
config:
  header_name: X-Correlation-ID
  generator: uuid#counter
  echo_downstream: true