apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: stel-ip-restriction
  namespace: stel-ns
plugin: ip-restriction
config:
  allow:
    - 127.0.0.1
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    # - 8.8.8.8         Dummy IP For Checks