kind: Deployment
apiVersion: apps/v1
metadata:
  name: cicd-compass-deployment
  namespace: compass
  labels:
    app: cicd-compass
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Max extra pods limit while update (1 extra pod will create)
      maxUnavailable: 0 # Max unavailable pods while update (Zero pods - zero downtime)
  selector:
    matchLabels:
      app: cicd-compass
  template:
    metadata:
      name: cicd-compass-pod
      labels:
        app: cicd-compass
    spec:
      containers:
        - name: cicd-compass-container
          image: sachinthokal/cicd-compass-app@sha256:e2610af28c89c76ece23741067fd5c0a87d9d19acf9305fd7a594e0da20db21e
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cicd-compass-configmap
          startupProbe:
            httpGet:
              path: /api/health
              port: 8080
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "750m"
              memory: "512Mi"
