kind: Deployment
apiVersion: apps/v1
metadata:
  name: cicd-compass-deployment
  namespace: compass
  labels:
    app: cicd-compass
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd-compass
  template:
    metadata:
      name: cicd-compass-pod
      labels:
        app: cicd-compass
    spec:
      containers:
        - name: cicd-compass-container
          image: sachinthokal/cicd-compass-app@sha256:0ba0e9821db72152b67f562256d3f857c4c8e31bb10be2df84f99b6457960beb
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cicd-compass-configmap

          startupProbe:
            httpGet:
              path: /api/health
              port: 8080
            failureThreshold: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 3
