kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: cicd-compass-pdb
  namespace: compass

spec:
  minAvailable: 1               # On the time of Maintenance minimum 1 pods will allow to stay always up & running.
  # minAvailable: "50%"         # We can give in percentage also, e.g., minAvailable: "50%")
  # maxUnavailable: 1           # On the time of Maintenance only max 1 pods will allow to get down.

  selector:
    matchLabels:
      app: cicd-compass