apiVersion: v1
kind: ConfigMap
metadata:
  name: cicd-compass-configmap
  namespace: compass
data:
  APP_NAME: "cicd-compass-app-prod"
  APP_ENVIRONMENT: "production-green"
  APP_VERSION: "v1.2.0"
  APP_REGION: "us-east-1"
  APP_BUILDNUMBER: "sha-9a422a8"
