kind: ConfigMap
apiVersion: v1
metadata:
  name: cicd-compass-configmap
  namespace: compass
data:
  application.properties: |
    # Application properties for CICD Compass
    APP_NAME="cicd-compass-prod"
    APP_ENV="production-k8s"
    APP_REGION="us-east-1"
    APP_VERSION="v1.0.0"
    APP_BUILD_NUMBER="build-1799"