apiVersion: v1
kind: ConfigMap
metadata:
  name: cicd-compass-configmap
  namespace: compass
data:
  APP_NAME: "cicd-compass-app-prod"
  APP_ENVIRONMENT: "production-k8s"
  APP_VERSION: "v1.0.0"
  APP_REGION: "us-east-1"
  APP_BUILDNUMBER: "sha-e073699"
