apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-compass-ingress
  namespace: compass
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicd-compass-stable-service   # cicd-compass-service
            port:
              number: 80